config/routes.rb
# encoding: utf-8
Mycrm::Application.routes.draw do

  get "home/index"
  root :to => "home#index"
  
  # 用户系统devise 重写了注册组件
  devise_for :users, :controllers => {:registrations => "registrations"} 
  
  devise_scope :user do
    # 等待邮箱验证
    match "awaiting_confirmation", :to => "registrations#awaiting_confirmation", :via => [:get], :as => "awaiting_confirmation"
    # 微博用户授权以后如果没有注册就会来这个地址注册
    # match "users/weibo_sign_up", :to => "registrations#weibo_new", :via => [:get], :as => "new_weibo_user_registration"       
  end

  # 管理员模块
  namespace :admin do
    root :to => "base#index"
    resources :users do
      # 角色分配
      get 'roles', :on => :member
      # 角色分配 写操作
      post 'assign_roles', :on => :member
      # 锁定用户
      post 'lock', :on => :member
      # 解锁用户
      post 'unlock', :on => :member
    end
    resources :roles do
      # 权限分配
      get 'permissions', :on => :member
      # 权限分配 写操作
      post 'assign_permissions', :on => :member
    end
    
    get "analytic/index"
    get "analytic/callcenter"
    get "analytic/cc"

    resources :permissions
  end

  # 市场模块
  namespace :marketing do
    root :to => "base#index"
    resources :bases
    
    # channel category
    resources :channel_categories
    # channel channel_infos
    resources :channel_infos
  end

  #客户信息模块
  namespace :client do
    root :to => "base#index" 
    # resource :base do 
    #   get 'all', :on => :collection
    # end
    
    #地区信息
    resources :common_districts
    #性格类型
    resources :character_types
    #申请院校
    resources :apply_colleages

    # 会话类型
    resources :session_types

    # 考试类型
    resources :exam_types

    # 未报名学生跟进
    resources :nssrs do 
      get 'all', :on => :collection
    end

    # 老学员跟进
    resources :oscfs do
      get 'all', :on => :collection
    end

    # 新学员跟进
    resources :nsfms do 
      get 'all', :on => :collection
    end


    #客户信息
    resources :infos  do
      get 'invit_index', :on => :collection
      get 'invit_search', :on => :collection
      get 'search_info', :on => :collection
      get 'cc_my', :on => :collection
      get 'cc_add_info', :on => :collection
      get 'channel_my', :on => :collection
      get 'signed', :on => :collection
      # 渠道，callcenter添加用户
      get 'channel_add_info', :on => :collection
      get 'callcenter_add_info', :on => :collection
      # 分配cc到给客户
      get 'distribute_cc', :on => :collection
      post 'save_distribute', :on => :collection

      # call center
      get 'callcenter_index', :on => :collection

      # 级联查询
      get 'get_city', :on => :collection
      get 'get_district', :on => :collection
      # 邀访
      resources :invations do 
        get 'come_directly', :on => :collection
        post 'save_directly', :on => :collection
      end
      # 客户信息包含很多会话
      resources :sessions do 
          # 每个会话有很多信息
          resources :records
      end
      # 培训经历
      resources :training_experiences
      # 考试成绩管理
      resources :exams do 
        resources :exam_details
      end

      # 给客户添加备注
      resources :info_notes
    end

  end
  
end

app/models/invation.rb
class Invation < ActiveRecord::Base
  # attr_accessible :come_time, :info_id, :invit_time, :status, :user_id
  belongs_to :user
  belongs_to :info
end

app/controllers/client/apply_colleages_controller.rb
# encoding: utf-8
class Client::ApplyColleagesController < Client::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource


  def index
    @apply_colleages = ApplyColleage.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @apply_colleage = ApplyColleage.find(params[:id])
  end

  def new
    @apply_colleage = ApplyColleage.new
  end

  def edit
    @apply_colleage = ApplyColleage.find(params[:id])
  end

  def create
    @apply_colleage = ApplyColleage.new(params[:apply_colleage])

    respond_to do |format|
      if @apply_colleage.save
        format.html { redirect_to client_apply_colleage_path(@apply_colleage), notice: 'Exam type was successfully created.' }
        format.json { render json: @apply_colleage, status: :created, location: @apply_colleage }
      else
        format.html { render action: "new" }
        format.json { render json: @apply_colleage.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @apply_colleage = ApplyColleage.find(params[:id])

    respond_to do |format|
      if @apply_colleage.update_attributes(params[:apply_colleage])
        format.html { redirect_to client_apply_colleage_path(@apply_colleage), notice: 'Exam type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apply_colleage.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @apply_colleage = ApplyColleage.find(params[:id])
    @apply_colleage.destroy

    respond_to do |format|
      format.html { redirect_to client_apply_colleages_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/client/base_controller.rb
# encoding: utf-8
class Client::BaseController < ApplicationController
  # 导航样式需要
  before_filter :action_for_nav

  def index
  end

  def invitations
  	@invations = @info.invations.paginate(:page => params[:page], :per_page => 20)
  end
  
  private
  def action_for_nav
  	@resource_name = 'Client'
  end
end

app/controllers/client/character_types_controller.rb
# encoding: utf-8
class Client::CharacterTypesController < Client::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource


  def index
    @character_types = CharacterType.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @character_type = CharacterType.find(params[:id])
  end

  def new
    @character_type = CharacterType.new
  end

  def edit
    @character_type = CharacterType.find(params[:id])
  end

  def create
    @character_type = CharacterType.new(params[:character_type])

    respond_to do |format|
      if @character_type.save
        format.html { redirect_to client_character_type_path(@character_type), notice: 'Exam type was successfully created.' }
        format.json { render json: @character_type, status: :created, location: @character_type }
      else
        format.html { render action: "new" }
        format.json { render json: @character_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @character_type = CharacterType.find(params[:id])

    respond_to do |format|
      if @character_type.update_attributes(params[:character_type])
        format.html { redirect_to client_character_type_path(@character_type), notice: 'Exam type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character_type.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @character_type = CharacterType.find(params[:id])
    @character_type.destroy

    respond_to do |format|
      format.html { redirect_to client_character_types_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/client/common_districts_controller.rb
# encoding: utf-8
class Client::CommonDistrictsController < Client::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource

  def index
  	@common_districts = CommonDistrict.paginate(:page => params[:page], :per_page => 20)
  end
  
end

app/controllers/client/exam_details_controller.rb
# encoding: utf-8
class Client::ExamDetailsController < Client::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource
  #authorize_resource
  
  def index
    @info = Info.find(params[:info_id])
    @exam = @info.exams.find(params[:exam_id])
    @exam_details = @exam.exam_details.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @exam_detail = ExamDetail.find(params[:id])
  end

  def new
    @info = Info.find(params[:info_id])
    @exam = @info.exams.find(params[:exam_id])
    @exam_detail = @exam.exam_details.new
  end

  def edit
    @info = Info.find(params[:info_id])
    @exam = @info.exams.find(params[:exam_id])
    @exam_detail = @exam.exam_details.find(params[:id])
  end

  def create
    @info = Info.find(params[:info_id])
    @exam = @info.exams.find(params[:exam_id])
    @exam_detail = @exam.exam_details.new(params[:exam_detail])

    respond_to do |format|
      if @exam_detail.save
        format.html { redirect_to client_info_exam_exam_detail_path(@info, @exam, @exam_detail) , notice: 'ExamDetail was successfully created.' }
        format.json { render json: @exam_detail, status: :created, location: @exam_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @exam_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @info = Info.find(params[:info_id])
    @exam = @info.exams.find(params[:exam_id])
    @exam_detail = @exam.exam_details.find(params[:id])

    respond_to do |format|
      if @exam_detail.update_attributes(params[:exam_detail])
        format.html { redirect_to client_info_exam_exam_detail_path(@info, @exam, @exam_detail), notice: 'ExamDetail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @info = Info.find(params[:info_id])
    @exam = @info.exams.find(params[:exam_id])
    @exam_detail = @exam.exam_details.find(params[:id])
    @exam_detail.destroy

    respond_to do |format|
      format.html { redirect_to client_info_exam_exam_details_path(@info, @exam) }
      format.json { head :no_content }
    end
  end
end

# class ExamDetailsController < ApplicationController
#   # GET /exam_details
#   # GET /exam_details.json
#   def index
#     @exam_details = ExamDetail.all

#     respond_to do |format|
#       format.html # index.html.erb
#       format.json { render json: @exam_details }
#     end
#   end

#   # GET /exam_details/1
#   # GET /exam_details/1.json
#   def show
#     @exam_detail = ExamDetail.find(params[:id])

#     respond_to do |format|
#       format.html # show.html.erb
#       format.json { render json: @exam_detail }
#     end
#   end

#   # GET /exam_details/new
#   # GET /exam_details/new.json
#   def new
#     @exam_detail = ExamDetail.new

#     respond_to do |format|
#       format.html # new.html.erb
#       format.json { render json: @exam_detail }
#     end
#   end

#   # GET /exam_details/1/edit
#   def edit
#     @exam_detail = ExamDetail.find(params[:id])
#   end

#   # POST /exam_details
#   # POST /exam_details.json
#   def create
#     @exam_detail = ExamDetail.new(params[:exam_detail])

#     respond_to do |format|
#       if @exam_detail.save
#         format.html { redirect_to @exam_detail, notice: 'Exam detail was successfully created.' }
#         format.json { render json: @exam_detail, status: :created, location: @exam_detail }
#       else
#         format.html { render action: "new" }
#         format.json { render json: @exam_detail.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PUT /exam_details/1
#   # PUT /exam_details/1.json
#   def update
#     @exam_detail = ExamDetail.find(params[:id])

#     respond_to do |format|
#       if @exam_detail.update_attributes(params[:exam_detail])
#         format.html { redirect_to @exam_detail, notice: 'Exam detail was successfully updated.' }
#         format.json { head :no_content }
#       else
#         format.html { render action: "edit" }
#         format.json { render json: @exam_detail.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /exam_details/1
#   # DELETE /exam_details/1.json
#   def destroy
#     @exam_detail = ExamDetail.find(params[:id])
#     @exam_detail.destroy

#     respond_to do |format|
#       format.html { redirect_to exam_details_url }
#       format.json { head :no_content }
#     end
#   end
# end

app/controllers/client/exam_types_controller.rb
# encoding: utf-8
class Client::ExamTypesController < Client::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource
  #authorize_resource

  def index
    @exam_types = ExamType.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @exam_type = ExamType.find(params[:id])
  end

  def new
    @exam_type = ExamType.new
  end

  def edit
    @exam_type = ExamType.find(params[:id])
  end

  def create
    @exam_type = ExamType.new(params[:exam_type])

    respond_to do |format|
      if @exam_type.save
        format.html { redirect_to client_exam_type_path(@exam_type), notice: 'Exam type was successfully created.' }
        format.json { render json: @exam_type, status: :created, location: @exam_type }
      else
        format.html { render action: "new" }
        format.json { render json: @exam_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @exam_type = ExamType.find(params[:id])

    respond_to do |format|
      if @exam_type.update_attributes(params[:exam_type])
        format.html { redirect_to client_exam_type_path(@exam_type), notice: 'Exam type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam_type.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @exam_type = ExamType.find(params[:id])
    @exam_type.destroy

    respond_to do |format|
      format.html { redirect_to client_exam_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/client/info_notes_controller.rb
# encoding: utf-8
class Client::InfoNotesController < Client::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource
  #authorize_resource

  def index
    @info = Info.find(params[:info_id])

    if [1, 4, 5].include?current_user.roles[0].id
      @info_notes = @info.info_notes.paginate(:page => params[:page], :per_page => 20)
    else
      @info_notes = @info.info_notes.where("cc_id = #{current_user.id}").paginate(:page => params[:page], :per_page => 20)
    end
  end

  def show
    @info_note = InfoNote.find(params[:id])
  end


  def new
    @info =  Info.find(params[:info_id])
    @info_note = @info.info_notes.new
  end

  def edit
    @info = Info.find(params[:info_id])
    @info_note = @info.info_notes.find(params[:id])
    if current_user.id != @info_note.cc_id
      flash[:notice] = "对不起，您只能修改自己的备注！"
      redirect_to client_info_info_notes_url
    end
  end

  def create
    @info = Info.find(params[:info_id])
    # date1 = DateTime.strptime(params[:info_note]['info_note_time'] + " CCT", "%Y-%m-%d %H:%M %Z")
    # params[:info_note]['info_note_time'] = date1
    @info_note = @info.info_notes.new(params[:info_note])

    respond_to do |format|
      if @info_note.save
        format.html { redirect_to client_info_info_note_path(@info, @info_note), notice: '成功添加备注！' }
        format.json { render json: @info_note, status: :created, location: @info_note }
      else
        format.html { render action: "new" }
        format.json { render json: @info_note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # date1 = DateTime.strptime(params[:info_note]['info_note_time'] + " CCT", "%Y-%m-%d %H:%M %Z")
    # params[:info_note]['info_note_time'] = date1
    @info = Info.find(params[:info_id])
    @info_note = @info.info_notes.find(params[:id])

    respond_to do |format|
      if @info_note.update_attributes(params[:info_note])
        format.html { redirect_to client_info_info_note_path(@info, @info_note), notice: 'InfoNote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info_note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @info = Info.find(params[:info_id])
    @info_note = @info.info_notes.find(params[:id])
    if current_user.id != @info_note.cc_id
      flash[:notice] = "对不起，您只能删除自己的备注！"
    else
      @info_note.destroy
    end

    respond_to do |format|
      format.html { redirect_to client_info_info_notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invations_helper.rb
module InvationsHelper
end

app/views/client/invations/_form.html.erb
<script type="text/javascript">
    $(function() {
            $( "#datepicker_1" ).datetimepicker();
            $( "#datepicker_1" ).datetimepicker( "option", "dateFormat", "yy-mm-dd" );
            $("form").submit(function(e){
               if($( "#datepicker_1" ).val() == ""){
                  alert("请选择时间!");
                  $( "#datepicker_1" ).focus();
                  return false;
               }
            });
    });
</script>

<div class="grid_5">
  <div class="module">
  <h2><span>客户考试</span></h2>

    <div class="module-body">
        <%= form_for([:client, @info, @invation]) do |f| %>

          <%= f.hidden_field :info_id, :value => "#{@info.id}" %>

          <p>
            <label>预约时间</label>
            <input type="text" id="datepicker_1" name="invation[invit_time]" />
          </p>

          <fieldset>
              <input class="submit-green" type="submit" value="Submit" /> 
              <input class="submit-gray" type="submit" value="Cancel" />
          </fieldset> 

          <% end %>
        </div>
        </div> <!-- End .module-body -->
    </div> <!-- End .module -->
  <div style="clear:both;"></div>
</div> <!-- End .grid_6 -->
<div style="clear:both;"></div>

app/views/client/invations/come_directly.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#edit_").validationEngine();
  });
</script> 
<script type="text/javascript">
    $(function() {
            $( "#datepicker_1" ).datetimepicker();
            $( "#datepicker_1" ).datetimepicker( "option", "dateFormat", "yy-mm-dd" );
            $("form").submit(function(e){
               if($( "#datepicker_1" ).val() == ""){
                  alert("请选择时间!");
                  $( "#datepicker_1" ).focus();
                  return false;
               }
            });
    });
</script>


<div class="grid_5">
  <div class="module">
  <h2><span></span></h2>

    <div class="module-body">
        <%= form_tag(save_directly_client_info_invations_path(@info), :method => :post) do%>

          <%= hidden_field_tag :info_id, :value => "#{@info.id}" %>

          <p>
            <label>到访状态</label>
            <%= select_tag :status, options_for_select([["已经到访", 1]]) %>
          </p>
          <p>
            <label>到访时间</label>
            <input type="text" id="datepicker_1" name="invation[come_time]" />
          </p>

          <fieldset>
              <input class="submit-green" type="submit" value="Submit" /> 
              <input class="submit-gray" type="reset" value="Cancel" />
          </fieldset> 

          <% end %>
        </div>
        </div> <!-- End .module-body -->
    </div> <!-- End .module -->
  <div style="clear:both;"></div>
</div> <!-- End .grid_6 -->
<div style="clear:both;"></div>

app/views/client/invations/edit.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#edit_").validationEngine();
  });
</script> 
<script type="text/javascript">
    $(function() {
            $( "#datepicker_1" ).datetimepicker();
            $( "#datepicker_1" ).datetimepicker( "option", "dateFormat", "yy-mm-dd" );
            $("form").submit(function(e){
               if($( "#datepicker_1" ).val() == ""){
                  alert("请选择时间!");
                  $( "#datepicker_1" ).focus();
                  return false;
               }
            });
    });
</script>

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= invit_index_client_infos_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>
                    
                </div>
            </div>


        <div class="grid_5">
          <div class="module">
          <h2><span></span></h2>

            <div class="module-body">
                <%= form_for([:client, @info, @invation]) do |f| %>

                  <%= f.hidden_field :info_id, :value => "#{@info.id}" %>

                  <p>
                    <label>到访状态</label>
                    <%= f.select :status,[["已经到访", 1]]%>
                  </p>
                  <%= f.hidden_field :user_id, :value => "#{current_user.id}"%>
                  <p>
                    <label>到访时间</label>
                    <input type="text" id="datepicker_1" name="invation[come_time]" />
                  </p>

                  <fieldset>
                      <input class="submit-green" type="submit" value="Submit" /> 
                      <input class="submit-gray" type="reset" value="Cancel" />
                  </fieldset> 

                  <% end %>
                </div>
                </div> <!-- End .module-body -->
            </div> <!-- End .module -->
          <div style="clear:both;"></div>
        </div> <!-- End .grid_6 -->
        <div style="clear:both;"></div>

app/views/client/invations/index.html.erb
        <!-- Initiate tablesorter script -->
        <script type="text/javascript">
            $(document).ready(function() { 
                $("#myTable") 
                .tablesorter({
                    // zebra coloring
                    widgets: ['zebra'],
                    // pass the headers argument and assing a object 
                    headers: { 
                        // assign the sixth column (we start counting zero) 
                        6: { 
                            // disable it by setting the property sorter to false 
                            sorter: false 
                        } 
                    }
                });
            //.tablesorterPager({container: $("#pager")}); 
        }); 
        </script>

<div class="grid_12">

    <div class="bottom-spacing">

        <!-- Button -->
        <div class="float-left">
            <a href="<%= new_client_info_invation_path %>" class="button">
              <span>添加预约<img src="<%= Mycrm::Application.config.staticfile_server_url %>admin_style/images/plus-small.gif" width="12" height="9" alt="New exams" /></span>
            </a>
        </div>

    </div>

    <div class="module">
        <h2><span>预约管理</span></h2>

        <div class="module-table-body">

            <table id="myTable" class="tablesorter">
              <thead>
                    <tr>
                        <th style="width:5%">ID</th>
                        <th style="width:5%">客户姓名</th>
                        <th style="width:5%">预约人</th>
                        <th style="width:5%">状态</th>
                        <th style="width:15%">预约时间</th>
                        <th style="width:15%">创建日期</th>
                        <th style="width:15%">最后更新</th>
                        <th style="width:10%">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <% @invations.each do |invation| %>
                    <tr>
                        <td class="align-center"><%= link_to invation.id, client_info_invation_path(@info, invation)%></td>
                        <td><%= invation.info.name %></td>
                        <td>
                            <% if invation.user_id%>
                                <%= User.find(invation.user_id).username %>
                            <% end %>
                        </td>
                        <td><%= invation.status==1 ? "已到访" : "未到访" %></td>
                        <td>
                            <% if invation.invit_time%>
                            <%= invation.invit_time.strftime('%Y-%m-%d %H:%M') %>
                            <% end %>
                        </td>
                        <td><%= invation.created_at.strftime('%Y-%m-%d') %></td>
                        <td><%= invation.updated_at.strftime('%Y-%m-%d') %></td>
                        <td>
                            <%= link_to '删除', client_info_invation_path(@info, invation), confirm: 'Are you sure?', method: :delete %>
                        </td>
                    </tr> 
                    <% end %>                             
                </tbody>
            </table>
            
            <div style="clear: both"></div>
        </div> <!-- End .module-table-body -->
    </div> <!-- End .module -->

</div> <!-- End .grid_12 -->
<div style="clear: both"></div>

<div class="apple_pagination">
    <%=h will_paginate @invations, :previous_label => '上一页',  :next_label => '下一页'%>
</div>

app/views/client/invations/new.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#new_exam").validationEngine();
  });

</script> 			
<div class="grid_12">
	<div class="bottom-spacing">
        <a href="<%= client_info_invations_path %>" class="button">
          <span>返回</span>
        </a>
    </div>
</div>
<%= render 'form' %>

app/views/client/invations/show.html.erb
<div class="grid_12">
    <div class="bottom-spacing">
        <a href="<%= client_info_invations_path %>" class="button">
          <span>返回</span>
        </a>
    </div>
</div>
<div class="grid_5">

    <div class="module">
         <h2><span>预约</span></h2>

         <div class="module-body">
            <p>
        <div>预约客户:<%= @invation.info.name %></div>
      </p>
      <p>
        <div>预约时间:<%= @invation.invit_time.strftime('%Y-%m-%d %H:%M')  %></div>
      </p>

         </div> <!-- End .module-body -->
    </div> <!-- End .module -->
    <div style="clear:both;"></div>
</div> <!-- End .grid_6 -->
<div style="clear:both;"></div>