config/routes.rb
# encoding: utf-8
Mycrm::Application.routes.draw do

  get "home/index"
  root :to => "home#index"
  
  # 用户系统devise 重写了注册组件
  devise_for :users, :controllers => {:registrations => "registrations"} 
  
  devise_scope :user do
    # 等待邮箱验证
    match "awaiting_confirmation", :to => "registrations#awaiting_confirmation", :via => [:get], :as => "awaiting_confirmation"
    # 微博用户授权以后如果没有注册就会来这个地址注册
    # match "users/weibo_sign_up", :to => "registrations#weibo_new", :via => [:get], :as => "new_weibo_user_registration"       
  end

  # 管理员模块
  namespace :admin do
    root :to => "base#index"
    resources :users do
      # 角色分配
      get 'roles', :on => :member
      # 角色分配 写操作
      post 'assign_roles', :on => :member
      # 锁定用户
      post 'lock', :on => :member
      # 解锁用户
      post 'unlock', :on => :member
    end
    resources :roles do
      # 权限分配
      get 'permissions', :on => :member
      # 权限分配 写操作
      post 'assign_permissions', :on => :member
    end
    
    get "analytic/index"
    get "analytic/callcenter"
    get "analytic/cc"

    resources :permissions
  end

  # 市场模块
  namespace :marketing do
    root :to => "base#index"
    resources :bases
    
    # channel category
    resources :channel_categories
    # channel channel_infos
    resources :channel_infos
  end

  #客户信息模块
  namespace :client do
    root :to => "base#index" 
    # resource :base do 
    #   get 'all', :on => :collection
    # end
    
    #地区信息
    resources :common_districts
    #性格类型
    resources :character_types
    #申请院校
    resources :apply_colleages

    # 会话类型
    resources :session_types

    # 考试类型
    resources :exam_types

    # 未报名学生跟进
    resources :nssrs do 
      get 'all', :on => :collection
    end

    # 老学员跟进
    resources :oscfs do
      get 'all', :on => :collection
    end

    # 新学员跟进
    resources :nsfms do 
      get 'all', :on => :collection
    end


    #客户信息
    resources :infos  do
      get 'invit_index', :on => :collection
      get 'invit_search', :on => :collection
      get 'search_info', :on => :collection
      get 'cc_my', :on => :collection
      get 'cc_add_info', :on => :collection
      get 'channel_my', :on => :collection
      get 'signed', :on => :collection
      # 渠道，callcenter添加用户
      get 'channel_add_info', :on => :collection
      get 'callcenter_add_info', :on => :collection
      # 分配cc到给客户
      get 'distribute_cc', :on => :collection
      post 'save_distribute', :on => :collection

      # call center
      get 'callcenter_index', :on => :collection

      # 级联查询
      get 'get_city', :on => :collection
      get 'get_district', :on => :collection
      # 邀访
      resources :invations do 
        get 'come_directly', :on => :collection
        post 'save_directly', :on => :collection
      end
      # 客户信息包含很多会话
      resources :sessions do 
          # 每个会话有很多信息
          resources :records
      end
      # 培训经历
      resources :training_experiences
      # 考试成绩管理
      resources :exams do 
        resources :exam_details
      end

      # 给客户添加备注
      resources :info_notes
    end

  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  # attr_accessible :title, :body
  has_and_belongs_to_many :users, :join_table => 'users_roles'
  has_and_belongs_to_many :permissions, :join_table => 'roles_permissions'
end

app/controllers/admin/roles_controller.rb
# encoding: utf-8
class Admin::RolesController < Admin::BaseController
  # before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  # load_and_authorize_resource
  #authorize_resource

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to admin_roles_url , notice: 'Role was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # 查找所有角色的权限
  def permissions
    @role = Role.find(params[:id])
    @permissions_all = Permission.all
    @permissions_role = @role.permissions
  end
  # 保存角色权限分配
  def assign_permissions
    if current_user.roles.include?(Role.find(1))
      @role = Role.find(params[:id])
      # 拿出此次得到权限数组
      permission_ids = params[:permission_ids]
      # 删除原来所有的关系
      @role.permissions.delete(@role.permissions)
      if not permission_ids.nil?
        permission_ids.each do |permission_id| 
          permission = Permission.find_by_id(permission_id)
          @role.permissions << permission
          # unless @user.roles.include? role
          #   @user.roles << role
          # end     
        end
      end
      redirect_to admin_role_path(@role)
    else
      flash[:notice] = "对不起，您没有权限修改！" 
      redirect_to admin_users_url
    end
  end
end

app/views/admin/roles/_form.html.erb
                <div class="grid_5">
                <div class="module">
                     <h2><span>角色管理</span></h2>
                        
                     <div class="module-body">
                        <%= form_for([:admin, @role]) do |f| %>
                          <% if @role.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

                              <ul>
                              <% @role.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                              <% end %>
                              </ul>
                            </div>
                            
                          <% end %>
                        
                            <p>
                                <label>角色名</label>
                                <%= f.text_field :rolename , :class => "input-medium validate[required,minSize[2],maxSize[30]" %>
                            </p>
                            <p>
                                <label>角色描述</label>
                                <%= f.text_field :roledesc %>
                            </p>

                            <fieldset>
                                <input class="submit-green" type="submit" value="Submit" /> 
                                <input class="submit-gray" type="submit" value="Cancel" />
                            </fieldset>
                        <% end %>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>

app/views/admin/roles/edit.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#edit_role_<%= @role.id %>").validationEngine();
  });

</script> 

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_roles_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <a href="<%= admin_role_path(@role) %>" class="button">
                          <span>查看</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
            </div>

<%= render 'form' %>

app/views/admin/roles/index.html.erb
        <!-- Initiate tablesorter script -->
        <script type="text/javascript">
            $(document).ready(function() { 
                $("#myTable") 
                .tablesorter({
                    // zebra coloring
                    widgets: ['zebra'],
                    // pass the headers argument and assing a object 
                    headers: { 
                        // assign the sixth column (we start counting zero) 
                        6: { 
                            // disable it by setting the property sorter to false 
                            sorter: false 
                        } 
                    }
                });
            //.tablesorterPager({container: $("#pager")}); 
        }); 
        </script>

            <div class="grid_12">
                
                <div class="bottom-spacing">
                
                    <!-- Button -->
                    <div class="float-left">
                        <a href="<%= new_admin_role_path %>" class="button">
                          <span>新建角色<img src="<%= Mycrm::Application.config.staticfile_server_url %>admin_style/images/plus-small.gif" width="12" height="9" alt="New article" /></span>
                        </a>
                    </div>
                    
                    
                    
                </div>
                
                
                <!-- Example table -->
                <div class="module">
                  <h2><span>角色管理</span></h2>
                    
                    <div class="module-table-body">

                        <table id="myTable" class="tablesorter">
                          <thead>
                                <tr>
                                    <th style="width:5%">ID</th>
                                    <th style="width:20%">角色名</th>
                                    <th style="width:21%">角色描述</th>
                                    <th style="width:13%">创建日期</th>
                                    <th style="width:13%">最后更新</th>
                                    <th style="width:15%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @roles.each do |role| %>
                                <tr>
                                    <td class="align-center"><%= role.id %></td>
                                    <td><a href=""><%= link_to role.rolename, [:admin, role] %></a></td>
                                    <td><%= link_to role.roledesc, [:admin, role] %></td>
                                    <td><%= role.created_at.strftime('%Y-%m-%d %H:%M') %></td>
                                    <td><%= role.updated_at.strftime('%Y-%m-%d %H:%M') %></td>
                                    <td>
                                      <%= link_to "编辑", edit_admin_role_path(role) %> |
                                      <%= link_to "权限分配", permissions_admin_role_path(role) %> |
                                      <%= link_to "删除", admin_role_path(role), :method => :delete, :confirm => "你确定要删除此角色?" %>
                                    </td>
                                </tr> 
                                <% end %>                             
                            </tbody>
                        </table>
                        
                        <div style="clear: both"></div>
                     </div> <!-- End .module-table-body -->
                </div> <!-- End .module -->
                
                <div style="clear: both"></div>

                <div class="apple_pagination">
                    <%=h will_paginate @roles, :previous_label => '上一页',  :next_label => '下一页'%>
                </div>
                
                

                
            </div> <!-- End .grid_12 -->
            <div style="clear: both"></div>

app/views/admin/roles/new.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#new_role").validationEngine();
  });

</script> 

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_roles_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
            </div>
<%= render 'form' %>

app/views/admin/roles/permissions.html.erb
			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_roles_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>
                </div>
            </div>

			<div class="grid_12">

                <div class="module">
                     <h2><span>角色 <%= @role.rolename %>的权限分配情况</span></h2>
                        
                     <div class="module-body">
                        
						<%= form_tag(assign_permissions_admin_role_path, :method => "post") do %>
						<table id="myTable" class="tablesorter">
                          <thead>
                                <tr>
                                    <th style="width:5%">ID</th>
                                    <th style="width:20%">权限名</th>
                                    <th style="width:21%">资源</th>
                                    <th style="width:13%">操作</th>
                                    <th style="width:13%">描述</th>
                                    <th style="width:13%">资源id</th>
                                    <th style="width:15%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @permissions_all.each do |permission| %>
                                <tr>
                                    <td class="align-center"><%= permission.id %></td>
                                    <td><%= permission.name %></td>
                                    <td><%= permission.subject_class %></td>
                                    <td><%= permission.action %></td>
                                    <td><%= permission.description %></td>
                                    <td><%= permission.subject_id %></td>
                                    <td>
                                      <%= check_box_tag('permission_ids[]', permission.id, @permissions_role.include?(permission)) %>
                                    </td>
                                </tr> 
                                <% end %>                             
                            </tbody>
                        </table>
                        	<fieldset>
                                <input class="submit-green" type="submit" value="Submit" /> 
                                <input class="submit-gray" type="submit" value="Cancel" />
                            </fieldset>
                        <% end %>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>

app/views/admin/roles/show.html.erb
			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_roles_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <a href="<%= edit_admin_role_path(@role) %>" class="button">
                          <span>编辑</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <%= link_to admin_role_path(@role), :method => :delete,
:confirm => "你确定要删除此角色?" , :class => 'button' do %>
						<span>删除角色</span>
						<% end %>
                    </div>
                    
                    
                    
                </div>
            </div>

			<div class="grid_5">

                <div class="module">
                     <h2><span>查看角色 <%= @role.rolename %></span></h2>
                        
                     <div class="module-body">
                        <p>
							<div>角色:<%= @role.rolename %></div>
						</p>
						<p>
							<div>描述:<%= @role.roledesc %></div>
						</p>
						<p>
							<div>权限:
								<% @role.permissions.each do |permisson| %>
								<%= permisson.name %>
								<% end %>

							</div>
						</p>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>